export const AUTHENTICATE = 'AUTHENTICATE';

export const GET_POSTS = 'GET_POSTS';

export const UPDATE_BODY = 'UPDATE_BODY';
export const SAVE_POST = 'SAVE_POST';
export const UPDATE_ACTIVE_THREAD_ID = 'UPDATE_ACTIVE_THREAD_ID';
export const ASSIGN_ALIAS = 'ASSIGN_ALIAS';
